### ISSUE TITLE
Button not working

### ISSUE THREAD

**Issue by tfhvie** [PtrBld/MMM-Button#10]
I've installed the Button module and connected the button to the Pi. In the config file I added the required lines to include the module (Pin number). Unfortunately the Pi doesn't recognise the button-press: there is no message appearing in the console log or console info. 
What is the issue?
Do I have to implement the python file, described in the link, into the .js file of the button module?

**Comment by domebe** [comment]
I have the same problem. 
Button on GPIO 5 (Pin29) and GND (Pin 30).
No response or any logs.

**Comment by balassy** [comment]
I fixed an error in this module and submitted a PR into the original repo, but given that I had not received any feedback in 18 days (I know it's summer time), and that this bug may affect others, let me comment here that you can find the fix on the `bugfix/this-reference-error` branch in my forked clone of this repo: https://github.com/balassy/MMM-Button/tree/bugfix/this-reference-error

**Comment by PtrBld** [comment]
Sorry I am under heavy load atm and forgot about your PR. You are totally right though and I just merged your changes. Thank you!

**Comment by balassy** [comment]
Thank you! 👍
