### ISSUE TITLE
MMM-Button doesnt work - NODE_MODULE_VERSION missmatch

### ISSUE THREAD

**Issue by cruunnerr** [PtrBld/MMM-Button#3]
Hello,

i got my MagicMirror run and now want to use the Button Module. Unfortunatly it doesnt’t work. And sorry for my english, it isnt very well.

I use a RPi 2

I did the “Complete Setup Tutorial” to set up the pi. Now when i try to put the module-code from the Button-Module into the config.js and do a “pm2 restart mm” the screen went to the desktop and then it will show just a blank, white page on the monitor. Button is used like this, but with GPIO-5 : [https://dracarysdiy.files.wordpress.com/2016/03/button.jpg?w=474](url)
I can see that the Button works as i used “gpio read” to check it

Any idea? All other modules working fine

Also its NOT possible to get the webUI with connecting via another pc (192.168.178.230:8080). Here is a screen of my config: [https://forum.magicmirror.builders/uploads/files/1474909812019-mmm-button-resized.png](url)

**Comment by slampus** [comment]
I have exactly the same problem. my screen turns totaly white.

**Comment by israel05** [comment]
Same here, unable to read the GPIO status of GPIO17

**Comment by emosbek** [comment]
how do i even get the MMM-Button to know what module to show/hide?

**Comment by ar84** [comment]
same Problem. My Screen turns black and MM Crash. I think there is a problem with OnOff

**Comment by PtrBld** [comment]
Sry for the late response guys...
@ar84 : Can you please check this: https://www.npmjs.com/package/onoff, and send me the logs of your MM?
@emosbek : The module is currently only supported by MMM-Podcast

**Comment by ar84** [comment]
@PtrBld 

/home/pi/.pm2/logs/mm-error-0.log last 15 lines:
0|mm       | Error: The module '/home/pi/MagicMirror/modules/MMM-Button/node_mod                          ules/epoll/build/Release/epoll.node'
0|mm       | was compiled against a different Node.js version using
0|mm       | NODE_MODULE_VERSION 48. This version of Node.js requires
0|mm       | NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
0|mm       | the module (for instance, using `npm rebuild` or`npm install`).
0|mm       |     at process.module.(anonymous function) [as dlopen] (ELECTRON_AS                          AR.js:173:20)
0|mm       |     at Object.Module._extensions..node (module.js:598:18)
0|mm       |     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR                          .js:173:20)
0|mm       |     at Module.load (module.js:488:32)
0|mm       |     at tryModuleLoad (module.js:447:12)
0|mm       |     at Function.Module._load (module.js:439:3)
0|mm       |     at Module.require (module.js:498:17)
0|mm       |     at require (internal/module.js:20:19)
0|mm       |     at bindings (/home/pi/MagicMirror/modules/MMM-Button/node_modul                          es/bindings/bindings.js:76:44)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Button/                          node_modules/epoll/epoll.js:1:192)

/home/pi/.pm2/logs/mm-out-0.log last 15 lines:
0|mm       | > magicmirror@2.1.1 start /home/pi/MagicMirror
0|mm       | > sh run-start.sh
0|mm       |
0|mm       | Starting MagicMirror: v2.1.1
0|mm       | Loading config ...
0|mm       | Loading module helpers ...
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: MMM-Podcast
0|mm       | Loading module helpers ...
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: MMM-Podcast
0|mm       | Whoops! There was an uncaught exception...
0|mm       | MagicMirror will not quit, but it might be a good idea to check why                           this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHu                          b: https://github.com/MichMich/MagicMirror/issues
0|mm       | Launching application.

**Comment by PtrBld** [comment]
please update the moduel and try again with `npm rebuild`

**Comment by ar84** [comment]
Update via GitPull made in the folder MMM-Button and then executed npm rebuild. But no improvement

Screen still black and MM crashed.

It has perhaps to do with the different node.js versions??

0|mm       | Error: The module '/home/pi/MagicMirror/modules/MMM-Button/node_modules/epoll/build/Release/epoll.node'
0|mm       | was compiled against a different Node.js version using
0|mm       | NODE_MODULE_VERSION 48. This version of Node.js requires
0|mm       | NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
0|mm       | the module (for instance, using `npm rebuild` or`npm install`).
0|mm       |     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
0|mm       |     at Object.Module._extensions..node (module.js:598:18)
0|mm       |     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
0|mm       |     at Module.load (module.js:488:32)
0|mm       |     at tryModuleLoad (module.js:447:12)
0|mm       |     at Function.Module._load (module.js:439:3)
0|mm       |     at Module.require (module.js:498:17)
0|mm       |     at require (internal/module.js:20:19)
0|mm       |     at bindings (/home/pi/MagicMirror/modules/MMM-Button/node_modules/bindings/bindings.js:76:44)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Button/node_modules/epoll/epoll.js:1:192)

**Comment by MrJuless** [comment]
Hi guys,
i had exectly the same issue here. npm rebuild doesn't help.

What helped for me was to rebuild electron, take a look at [this](https://stackoverflow.com/questions/42616008/node-module-version-conflict-when-installing-modules-for-electron)

Now i have another problem, and no describtion. MagicMirror registers the Buttonclick but doesn't play the video:

`
0|MagicMir | button pressed
0|MagicMir | Whoops! There was an uncaught exception...
0|MagicMir | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|MagicMir | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
`
does anyone had this problem?

best,
jules

**Comment by MrJuless** [comment]
Ok, it didn't help. I also did en [upgrade ](http://thisdavej.com/upgrading-to-more-recent-versions-of-node-js-on-the-raspberry-pi/)to the latest nodejs.
Now i have the same error again but with version 51 and expectet 53...

best regards,
Jules

**Comment by PtrBld** [comment]
Please take a look at this issue:
https://github.com/paviro/MMM-PIR-Sensor/issues/28

**Comment by ar84** [comment]
ThanksMany Thanks
This was the solution to this error
