### ISSUE TITLE
Update node module version

### ISSUE THREAD

**Issue by faliko** [PtrBld/MMM-Button#4]
Hi !
I install your module but have a blanck screen. I am also a noob in raspberry.
 Apparently, the version of "node-module" is 46, and it would require version 53. After reinstalling and updating, nothing is done. An error occurs.
"_The module '/home/pi.../MM-button/node_modules/epoll/build/Release/epoll.node' was compiled against a different Node.JS version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 53. ..._

If you have an issues ...

Thank you !

**Comment by toniweser** [comment]
Got the same problem here. 
"... was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. ... "

**Comment by PtrBld** [comment]
Please consider issue #3 as it is about the same problem
