### ISSUE TITLE
Black screen, no module displayed

### ISSUE THREAD

**Issue by MichiMich** [PtrBld/MMM-Button#6]
Hy there,

i installed your MMM-Button and your MMM-Podcast program as mentioned. If I add the module MMM-Button to my config.js file with all default values and restart the mirror with 
DISPLAY=:0 npm start
The screen gets black and no module does show up. Even nothing with clicking the button. The modules worked all correctly before I added the MMM-Button module. If I delete the MMM-Button from my config.js file the mirror works like a charm. So I do not get your module started.

Best regards
Michael

**Comment by PtrBld** [comment]
Hi Michael,
i know that there are currently some problems with my modules. Since I am totally aware of the bugs and need them for my own project I will start reworking them soon. When I am finished I will inform you!
Best regards 
Peter

**Comment by MichiMich** [comment]
All right, thanks a lot. So i can stop searching for my fault :)

**Comment by PtrBld** [comment]
Hi, should work now.

**Comment by MichiMich** [comment]
So the other modules are working no, i added your Button and Podcast module like this in my config.js file:

modules: [
{
		module: 'MMM-Button',
		config: {
			// See 'Configuration options' for more information.
		}
	},
	{
		module: 'MMM-Podcast',
		config: {
			// See 'Configuration options' for more information.
		}
	}
]

And if i push the button (+3.3V to PIN 5) nothing changes. Do you have any idea why?

PS: Your link "how to connect a button" is invalid.

Thanks for your work

Regards Michael

**Comment by PtrBld** [comment]
Ok the how to connect a button link is fixed.
To be clear: You need to connect the button to PIN 5 and Ground since the needed voltage is supplied by PIN 5.
Furthermore you can see if the button click worked using `pm2 logs` since the button module will write a line to the console when a button press is recognized properly.

**Comment by MichiMich** [comment]
Thanks for that. Button pressed works, but i get the following warning

button pressed
Whoops! There was an uncaught exception...
ReferenceError: socketNotificationReceived is not defined
    at Timeout._onTimeout (/home/pi/MagicMirror/modules/MMM-Podcast/node_helper.js:32:27)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues


internet connection ist just fine, do you think its an error of the podcast module.

Thanks and regards

**Comment by PtrBld** [comment]
Yes it was... Should be fixed as well.
Can you try it again?

**Comment by MichiMich** [comment]
Hey there,

i tried again. Now i get the following error:

button pressed
Whoops! There was an uncaught exception...
TypeError: this.socketNotificationReceived is not a function
    at Timeout._onTimeout (/home/pi/MagicMirror/modules/MMM-Podcast/node_helper.js:32:32)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?


Regards Michael

**Comment by PtrBld** [comment]
All issues should be fixed
