### ISSUE TITLE
More than one button

### ISSUE THREAD

**Issue by sharma-ji** [PtrBld/MMM-Button#7]
I changed the code for more two buttons as follows: 

'use strict';

/* Magic Mirror
 * Module: MMM-Button
 *
 * MIT Licensed.
 */

const NodeHelper = require('node_helper');
const gpio = require('onoff');
module.exports = NodeHelper.create({
  start: function () {
    this.started = false
  },
  // Subclass socketNotificationReceived received.
  socketNotificationReceived: function(notification, payload) {
    const self = this;
    if (notification === 'BUTTON_CONFIG' && this.started == false) {     
		const self = this
		this.config = payload     	  
		var GPIO = require('onoff').Gpio,
		button = new GPIO(this.config.buttonPIN, 'in', 'both',{ persistentWatch: true, debounceTimeout: this.config.clickDelay });
		buttonn = new GPIO(this.config.buttonPINN, 'in', 'both',{ persistentWatch: true, debounceTimeout: this.config.clickDelay });
		button.watch(function(err, state) {
		  // check the state of the button
		  // 1 == pressed, 0 == not pressed
		  if(state == 1) {
			// send notification for broadcast
			self.sendSocketNotification("BUTTON_PRESSED", true);
			console.log("button pressed");
			}
		});  
        buttonn.watch(function(err, state) {
		  // check the state of the button
		  // 1 == pressed, 0 == not pressed
		  if(state == 1) {
			// send notification for broadcast
			self.sendSocketNotification("BUTTON_PRESSED", true);
			console.log("button 2 pressed");
			}
		});
		this.started = true
    };
  }
  
});

But it says, button is not defined in console. Can you please help me out with error?

This is main file:

/* global Module */

/* Magic Mirror
 * Module: MMM-Button
 *
 * MIT Licensed.
 */

Module.register('MMM-Button',{	
	requiresVersion: "2.1.0",
	defaults: {
		buttonPIN: 4,
                buttonPINN: 5,
		//time in miliseconds before another button click is recognized
		clickDelay: 500,		
	},	
	// Override socket notification handler.
	socketNotificationReceived: function(notification, payload) {
		if (notification === "BUTTON_PRESSED"){
			this.sendNotification(notification, payload)
		}
	},	
	start: function() {
		this.sendSocketNotification('BUTTON_CONFIG', this.config);
		Log.info('Starting module: ' + this.name);
	}
});

**Comment by PtrBld** [comment]
Sorry for the late response...

Try changing
`var GPIO = require('onoff').Gpio,
  button = new GPIO(this.config.buttonPIN, 'in', 'both',{ persistentWatch: true, debounceTimeout: this.config.clickDelay });
  buttonn = new GPIO(this.config.buttonPINN, 'in', 'both',{ persistentWatch: true, debounceTimeout: this.config.clickDelay });`

to 

`var GPIO = require('onoff').Gpio;  
  var button = new GPIO(this.config.buttonPIN, 'in', 'both',{ persistentWatch: true, debounceTimeout: this.config.clickDelay });
  var buttonn = new GPIO(this.config.buttonPINN, 'in', 'both',{ persistentWatch: true, debounceTimeout: this.config.clickDelay });`

**Comment by PtrBld** [comment]
Ok i have updated my code.
You can now specify the broadcast string in the config using notificationMessage which still defaults to "BUTTON_PRESSED". So you can just add 2 button modules to your mirror config with different notificationMessages should be much easier this way.

Does this answer your question?
