### ISSUE TITLE
Change pull_up_down-resistor

### ISSUE THREAD

**Issue by kaestners** [PtrBld/MMM-Button#8]
Hello,
at the first thanks for this module and your work and engineering.
My question is, where I can change the pull_up_down resistor?!
Background is that I have a PIR sensor and which this I will start your other Module MMM-Podcast on my mirror. But the PIR sensor work with 3,3 V and not with GND I think. And for this I must change the resistor Level.
I hope I´m right with my Idea ;)
Thanks a lot for your Help

**Comment by PtrBld** [comment]
For PIR-Sensor please try [MMM-PIR-Sensor](https://github.com/paviro/MMM-PIR-Sensor) module by [paviro](https://github.com/paviro)
