### ISSUE TITLE
Where do I change what module is loaded? 

### ISSUE THREAD

**Issue by CharlesJGantt** [PtrBld/MMM-Button#9]
Hello, I am not great with Javascript, more of a Python guy, I have been trying to figure out for hours where you change which module the button press will load.  Can you help?

**Comment by PtrBld** [comment]
When pressed the button-module will broadcast "BUTTON_PRESSED" to every module. You need to change the code of the module you want to respond to the button click and set your action right there.

This would look something like this: 
  ```
notificationReceived: function(notification, payload, sender) {
		 ...
		//register to MMM-Button click
		if(notification == "BUTTON_PRESSED") {
			//Your code. Whatever you like, the module receiving the broadcast, to do.
		}
                ...
	},
```

I should add an option to change the broadcast string so one can use more than one button. Will probably do this if it is needed.

**Comment by PtrBld** [comment]
Ok i have updated the code. 
You can now specify the broadcast string in the config using notificationMessage which still defaults to "BUTTON_PRESSED".
